name: Release To Nuget

on:
  workflow_call:
    inputs:
        nuget-source:
            type: string
            default: https://api.nuget.org
        working-directory:
            type: string
            default: .
        version:
            type: string
            required: true

jobs:
  build-nuget:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ inputs.working-directory }}
    steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Ensure GitHub NuGet Source
          if: ${{ inputs.nuget-source != 'https://api.nuget.org' }}
          run: |
            dotnet nuget add source ${NUGET_SOURCE} \
            -n github \
            -u ${{ secrets.NUGET_USER }} \
            -p ${{ secrets.NUGET_TOKEN }} \
            --store-password-in-clear-text
          env:
            NUGET_SOURCE: ${{ inputs.nuget-source }}
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Pack
          run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
          env:
            VERSION: ${{ inputs.version }}
        - name: Push
          run: dotnet nuget push *.nupkg --source ${NUGET_SOURCE} --api-key ${NUGET_TOKEN} --skip-duplicate
          env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
            NUGET_SOURCE: ${{ inputs.nuget-source }}
