name: Test

on:
  workflow_call:
    inputs:
        working-directory:
          type: string
          default: .
        upload-coverage:
          type: string
          default: 'false'
        nuget-source:
          type: string
          default: ''

jobs:
  test-dotnet:
    name: Test

    runs-on: ubuntu-latest

    defaults:
      run:
          working-directory: ${{ inputs.working-directory }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Ensure GitHub NuGet Source
      if: ${{ inputs.nuget-source != '' }}
      run: |
        dotnet nuget add source ${NUGET_SOURCE} \
        -n github \
        -u ${{ secrets.NUGET_USER }} \
        -p ${{ secrets.NUGET_TOKEN }} \
        --store-password-in-clear-text
      env:
        NUGET_SOURCE: ${{ inputs.nuget-source }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=lcov"
    - name: Upload coverage reports to Codecov
      if: ${{ inputs.upload-coverage == 'true' }}
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
